---
apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: backend
  namespace: test
  labels:
    chart: podinfo
spec:
  chartGitPath: podinfo
  releaseName: backend
  values:
    replicaCount: 1
    image:
      tag: 0.2.2
