---
apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: cache
  namespace: test
  labels:
    chart: memcached
spec:
  chartGitPath: memcached
  releaseName: cache
  values:
    image: memcached:1.4.36-alpine
    replicaCount: 1
    pdbMinAvailable: 1
    AntiAffinity: "soft"
    memcached:
      maxItemMemory: 64
      verbosity: v
      extendedOptions: modern
